version: '3.8'

services:
  bird-meteo:
    build: .
    image: bird-meteo:latest
    volumes:
      - ./.streamlit:/app/.streamlit
    restart: unless-stopped
    network_mode: service:tailscale
    depends_on:
      - tailscale

# Tailscale service to expose webserver to the internet
  tailscale:
    image: tailscale/tailscale:latest
    hostname: bird-meteo
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped

volumes:
  tailscale-state: