import streamlit as st
import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from google import genai
from components.sidebar import render_sidebar
from src.config import SESSION_KEY_WEATHER_IMPACT, SESSION_KEY_COMPARE_REGIONS, GEMINI_MODEL_ID
from src.prompts import FINDINGS_PROMPT_TEMPLATE

st.set_page_config(page_title="Findings - Bird & Weather Explorer", layout="wide")

filters = render_sidebar()

st.title("Key Findings")
st.markdown("Scientific summary generated by Google Gemini based on your analysis results.")

weather_impact = st.session_state.get(SESSION_KEY_WEATHER_IMPACT)
compare_regions = st.session_state.get(SESSION_KEY_COMPARE_REGIONS)

if not weather_impact and not compare_regions:
    st.info("Please run the Weather Impact and Compare Regions analyses first to generate findings.")
    st.stop()

data = {
    "species": filters["species"],
    "start_date": filters["start_date"],
    "end_date": filters["end_date"],
}

if weather_impact:
    data.update({
        "weather_param": weather_impact["weather_param"],
        "pearson_r": weather_impact["pearson_r"],
        "p_value_weather": weather_impact["p_value"],
        "n_weather": weather_impact["n"]
    })
else:
    data.update({
        "weather_param": "N/A",
        "pearson_r": 0.0,
        "p_value_weather": 1.0,
        "n_weather": 0
    })

if compare_regions:
    data.update({
        "region_a": compare_regions["region_a"],
        "region_b": compare_regions["region_b"],
        "metric": compare_regions["metric"],
        "t_statistic": compare_regions["t_statistic"],
        "p_value_regions": compare_regions["p_value"],
        "n_a": compare_regions["n_a"],
        "n_b": compare_regions["n_b"]
    })
else:
    data.update({
        "region_a": "N/A",
        "region_b": "N/A",
        "metric": "N/A",
        "t_statistic": 0.0,
        "p_value_regions": 1.0,
        "n_a": 0,
        "n_b": 0
    })

api_key = st.secrets.get("GEMINI_API_KEY")
if not api_key:
    st.error("GEMINI_API_KEY not found in secrets. Please add it to `.streamlit/secrets.toml`.")
    st.stop()

client = genai.Client(api_key=api_key)

if "last_summary" not in st.session_state:
    st.session_state.last_summary = None


def generate_summary():
    prompt = FINDINGS_PROMPT_TEMPLATE.format(**data)
    with st.spinner("Generating summary..."):
        try:
            response = client.models.generate_content(
                model=GEMINI_MODEL_ID,
                contents=prompt
            )
            st.session_state.last_summary = response.text
        except Exception as e:
            st.error(f"Error generating summary: {e}")


if st.button("Generate Summary"):
    generate_summary()

if st.session_state.last_summary:
    st.markdown("---")
    st.markdown(st.session_state.last_summary)

    if st.button("Regenerate Summary"):
        generate_summary()
        st.rerun()
